package main

import (
	"os"
	"strings"
	"testing"
)

const sampleChangelog = `<!-- This file is autogenerated. See CONTRIBUTING.md for instructions to add an entry. -->

# Changelog

<!-- next version -->

<!-- previous-version -->

## v0.43.0

Old content here.
`

func TestInsertChangelog_Basic(t *testing.T) {
	tmp := t.TempDir() + "/CHANGELOG.md"
	if err := os.WriteFile(tmp, []byte(sampleChangelog), 0o644); err != nil {
		t.Fatal(err)
	}

	content := "## v0.145.0\n\nSome generated content.\n"
	if err := InsertChangelog(tmp, content); err != nil {
		t.Fatalf("InsertChangelog: %v", err)
	}

	result, err := os.ReadFile(tmp)
	if err != nil {
		t.Fatal(err)
	}
	s := string(result)

	if !strings.Contains(s, "## v0.145.0") {
		t.Error("output missing inserted version header")
	}
	// Old content should still be there.
	if !strings.Contains(s, "## v0.43.0") {
		t.Error("old changelog entry should be preserved")
	}
	// next version marker should still be there.
	if !strings.Contains(s, "<!-- next version -->") {
		t.Error("<!-- next version --> marker should be preserved")
	}
	// previous-version marker should still be there.
	if !strings.Contains(s, "<!-- previous-version -->") {
		t.Error("<!-- previous-version --> marker should be preserved")
	}
	// Inserted content should appear between the two markers.
	nextIdx := strings.Index(s, "<!-- next version -->")
	prevIdx := strings.Index(s, "<!-- previous-version -->")
	contentIdx := strings.Index(s, "## v0.145.0")
	if contentIdx < nextIdx || contentIdx > prevIdx {
		t.Error("inserted content should appear between <!-- next version --> and <!-- previous-version -->")
	}
}

func TestInsertChangelog_ReplacesExisting(t *testing.T) {
	// Simulate a CHANGELOG.md that already has a generated upstream section.
	existing := `<!-- This file is autogenerated. -->

# Changelog

<!-- next version -->

## v0.144.0

Old generated content.

#### Dynatrace distribution changelog:

<!-- previous-version -->

## v0.43.0
`
	tmp := t.TempDir() + "/CHANGELOG.md"
	if err := os.WriteFile(tmp, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	content := "## v0.145.0\n\nNew generated content.\n"
	if err := InsertChangelog(tmp, content); err != nil {
		t.Fatalf("InsertChangelog: %v", err)
	}

	result, err := os.ReadFile(tmp)
	if err != nil {
		t.Fatal(err)
	}
	s := string(result)

	if strings.Contains(s, "## v0.144.0") {
		t.Error("old generated section should have been replaced")
	}
	if !strings.Contains(s, "## v0.145.0") {
		t.Error("new generated content should be present")
	}
	if !strings.Contains(s, "## v0.43.0") {
		t.Error("original older entry should be preserved")
	}
}

func TestInsertChangelog_MissingNextVersionMarker(t *testing.T) {
	tmp := t.TempDir() + "/CHANGELOG.md"
	if err := os.WriteFile(tmp, []byte("no markers here"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := InsertChangelog(tmp, "content")
	if err == nil {
		t.Error("expected error when <!-- next version --> marker is missing")
	}
}

func TestInsertChangelog_PreservesDistroEntries(t *testing.T) {
	// The distro entries added by chloggen sit between next version and
	// previous-version but before any upstream section.
	existing := `<!-- autogenerated -->

# Changelog

<!-- next version -->

### 💡 Enhancements 💡

- ` + "`config_examples`" + `: Some distro-specific change ([#809](url))

#### Dynatrace distribution changelog:

<!-- previous-version -->

## v0.43.0
`
	tmp := t.TempDir() + "/CHANGELOG.md"
	if err := os.WriteFile(tmp, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	content := "## v0.145.0\n\nUpstream content.\n"
	if err := InsertChangelog(tmp, content); err != nil {
		t.Fatalf("InsertChangelog: %v", err)
	}

	result, _ := os.ReadFile(tmp)
	s := string(result)

	if !strings.Contains(s, "config_examples") {
		t.Error("distro-specific entry should be preserved")
	}
	if !strings.Contains(s, "## v0.145.0") {
		t.Error("upstream content should be inserted")
	}
}

