package main

import (
	"os"
	"strings"
	"testing"
)

// sampleScaffold simulates a CHANGELOG.md produced by `make chlog-update`
// with a downstream entry plus the full upstream placeholder scaffold.
const sampleScaffold = `<!-- autogenerated -->

# Changelog

<!-- next version -->

## v0.45.0

<!-- upstream-start -->
This release includes version <!-- upstream-version --> of the upstream Collector components.

The individual upstream Collector changelogs can be found here:

<!-- upstream-collector-versions -->

<!-- upstream-breaking-changes -->

<details>
<summary>Highlights from the upstream Collector changelog</summary>

<!-- upstream-other-changes -->

---

</details>

<!-- upstream-end -->

#### Dynatrace distribution changelog:

### 💡 Enhancements 💡

- ` + "`config_examples`" + `: Some downstream change ([#809](url))

<!-- previous-version -->

## v0.44.0

Old content here.
`

// sampleScaffoldNoDownstream simulates a scaffold with no downstream entries
// (only the upstream section and the previous-version marker).
const sampleScaffoldNoDownstream = `<!-- autogenerated -->

# Changelog

<!-- next version -->

## v0.45.0

<!-- upstream-start -->
This release includes version <!-- upstream-version --> of the upstream Collector components.

The individual upstream Collector changelogs can be found here:

<!-- upstream-collector-versions -->

<!-- upstream-breaking-changes -->

<details>
<summary>Highlights from the upstream Collector changelog</summary>

<!-- upstream-other-changes -->

---

</details>

<!-- upstream-end -->
<!-- previous-version -->

## v0.44.0

Old content here.
`

func sampleUpstreamContent() UpstreamContent {
	return UpstreamContent{
		VersionIntro:      "v0.145.0",
		CollectorVersions: "v0.145.0:\n\n- <https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.145.0>\n- <https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.145.0>",
		BreakingChanges:   "### 🛑 Breaking changes 🛑\n\n- `processor/resourcedetection`: Some breaking change ([#1](url))",
		OtherChanges:      "### 💡 Enhancements 💡\n\n- `receiver/filelog`: Some enhancement ([#2](url))",
	}
}

func TestFillUpstreamPlaceholders_FillsVersionIntro(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	if err := FillUpstreamPlaceholders(tmp, sampleUpstreamContent()); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if !strings.Contains(s, "This release includes version v0.145.0 of the upstream") {
		t.Errorf("expected version intro to be filled in:\n%s", s)
	}
}

func TestFillUpstreamPlaceholders_FillsCollectorVersions(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	if err := FillUpstreamPlaceholders(tmp, sampleUpstreamContent()); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if !strings.Contains(s, "v0.145.0:") {
		t.Errorf("expected collector version links in output:\n%s", s)
	}
	if strings.Contains(s, "<!-- upstream-collector-versions -->") {
		t.Errorf("placeholder should be replaced:\n%s", s)
	}
}

func TestFillUpstreamPlaceholders_FillsBreakingChanges(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	if err := FillUpstreamPlaceholders(tmp, sampleUpstreamContent()); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if !strings.Contains(s, "processor/resourcedetection") {
		t.Errorf("expected breaking changes in output:\n%s", s)
	}
	if strings.Contains(s, "<!-- upstream-breaking-changes -->") {
		t.Errorf("placeholder should be replaced:\n%s", s)
	}
}

func TestFillUpstreamPlaceholders_FillsOtherChanges(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	if err := FillUpstreamPlaceholders(tmp, sampleUpstreamContent()); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if !strings.Contains(s, "receiver/filelog") {
		t.Errorf("expected other changes in output:\n%s", s)
	}
	if strings.Contains(s, "<!-- upstream-other-changes -->") {
		t.Errorf("placeholder should be replaced:\n%s", s)
	}
}

func TestFillUpstreamPlaceholders_RemovesBoundaryMarkers(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	if err := FillUpstreamPlaceholders(tmp, sampleUpstreamContent()); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if strings.Contains(s, "<!-- upstream-start -->") {
		t.Error("<!-- upstream-start --> boundary marker should be removed")
	}
	if strings.Contains(s, "<!-- upstream-end -->") {
		t.Error("<!-- upstream-end --> boundary marker should be removed")
	}
}

func TestFillUpstreamPlaceholders_PreservesDownstreamEntries(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	if err := FillUpstreamPlaceholders(tmp, sampleUpstreamContent()); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if !strings.Contains(s, "config_examples") {
		t.Error("downstream entry should be preserved")
	}
	if !strings.Contains(s, "## v0.44.0") {
		t.Error("previous release entry should be preserved")
	}
}

func TestFillUpstreamPlaceholders_NoUpstream_RemovesSection(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	if err := FillUpstreamPlaceholders(tmp, UpstreamContent{}); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if strings.Contains(s, "<!-- upstream-start -->") || strings.Contains(s, "<!-- upstream-end -->") {
		t.Error("boundary markers should be removed")
	}
	if strings.Contains(s, "<!-- upstream-version -->") ||
		strings.Contains(s, "<!-- upstream-collector-versions -->") ||
		strings.Contains(s, "<!-- upstream-breaking-changes -->") ||
		strings.Contains(s, "<!-- upstream-other-changes -->") {
		t.Error("all upstream placeholders should be removed")
	}
	if strings.Contains(s, "This release includes version") {
		t.Error("upstream intro text should be removed when no upstream release")
	}
}

func TestFillUpstreamPlaceholders_NoUpstream_PreservesDownstream(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	if err := FillUpstreamPlaceholders(tmp, UpstreamContent{}); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if !strings.Contains(s, "config_examples") {
		t.Error("downstream entry should be preserved after removing upstream section")
	}
	if !strings.Contains(s, "## v0.44.0") {
		t.Error("previous release should be preserved")
	}
}

func TestFillUpstreamPlaceholders_NoUpstream_NoDownstream(t *testing.T) {
	tmp := writeTmp(t, sampleScaffoldNoDownstream)
	if err := FillUpstreamPlaceholders(tmp, UpstreamContent{}); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if strings.Contains(s, "<!-- upstream") {
		t.Errorf("all upstream markers/placeholders should be removed:\n%s", s)
	}
	if !strings.Contains(s, "## v0.44.0") {
		t.Error("previous release should be preserved")
	}
}

func TestFillUpstreamPlaceholders_EmptyBreakingChanges_PlaceholderRemoved(t *testing.T) {
	tmp := writeTmp(t, sampleScaffold)
	uc := sampleUpstreamContent()
	uc.BreakingChanges = ""
	if err := FillUpstreamPlaceholders(tmp, uc); err != nil {
		t.Fatalf("FillUpstreamPlaceholders: %v", err)
	}
	s := readTmp(t, tmp)
	if strings.Contains(s, "<!-- upstream-breaking-changes -->") {
		t.Error("empty breaking-changes placeholder should be removed")
	}
}

func TestFillUpstreamPlaceholders_MissingMarkersNoUpstream_NoOp(t *testing.T) {
	// If chloggen did not produce a scaffold (no markers), removing the
	// upstream section should be a no-op rather than an error.
	content := "# Changelog\n\n## v0.44.0\n\nOld content.\n"
	tmp := writeTmp(t, content)
	if err := FillUpstreamPlaceholders(tmp, UpstreamContent{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	s := readTmp(t, tmp)
	if s != content {
		t.Errorf("content should be unchanged when markers are absent:\ngot:\n%s", s)
	}
}

// helpers

func writeTmp(t *testing.T, content string) string {
	t.Helper()
	path := t.TempDir() + "/CHANGELOG.md"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func readTmp(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
