name: "Create Kind Cluster"
description: "Creates a Kind cluster"
inputs:
  kind-version:
    required: false
    description: "Version of kind that should be used"
    # renovate: datasource=github-releases depName=kubernetes-sigs/kind
    default: "v0.18.0"
  k8s-version:
    required: false
    description: "Kubernetes version that should be used"
    # renovate: datasource=github-releases depName=kubernetes/kubernetes
    default: "v1.27.11"
  cluster-name:
    required: false
    description: "Name of the kind cluster"
    default: "kind"
env:
  GO_VERSION: "~1.22"
runs:
  using: "composite"
  steps:

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
        cache: false

    - name: Cache tools
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: .tools
        key: e2e-tools-${{ runner.os }}-${{ hashFiles('internal/tools/go.sum') }}

    - name: Install tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p .tools
        touch .tools/*
        make install-tools

    - name: "Create single kind Cluster"
      uses: helm/kind-action@v1.10.0
      with:
        cluster_name: ${{ inputs.cluster-name }}
        version: ${{ inputs.kind-version }}
        node_image: "kindest/node:${{ inputs.k8s-version }}"
        kubectl_version: ${{ inputs.k8s-version }}
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dynatrace-otel-collector-image
        path: /tmp

    - name: Load Image into Kind
      shell: bash
      run: |
        kind load image-archive /tmp/dynatrace-otel-collector.tar -n ${{ inputs.cluster-name }}
