name: "Create Kind Cluster"
description: "Creates a Kind cluster"
inputs:
  kind-version:
    required: false
    description: "Version of kind that should be used"
    # renovate: datasource=github-releases depName=kubernetes-sigs/kind
    default: "v0.30.0"
  k8s-version:
    required: false
    description: "Kubernetes version that should be used"
    # renovate: datasource=docker depName=kindest/node
    default: "v1.34.0"
  cluster-name:
    required: false
    description: "Name of the kind cluster"
    default: "kind"
  config:
    required: false
    description: "Config for the kind cluster"
    default: "./.github/actions/create-cluster/single-node.yaml"
env:
  # renovate: datasource=golang-version depName=go
  GO_VERSION: "1.25.1"
runs:
  using: "composite"
  steps:

    - name: Setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
        cache: false

    - name: Cache tools
      id: cache-tools
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: .tools
        key: e2e-tools-${{ runner.os }}-${{ hashFiles('internal/tools/go.sum') }}

    - name: Install tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p .tools
        touch .tools/*
        make install-tools

    - name: "Create single kind Cluster"
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        cluster_name: ${{ inputs.cluster-name }}
        version: ${{ inputs.kind-version }}
        node_image: "kindest/node:${{ inputs.k8s-version }}"
        kubectl_version: ${{ inputs.k8s-version }}
        config: ${{ inputs.config }}
    
    - name: Download artifact
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: dynatrace-otel-collector-image
        path: /tmp

    - name: Load Image into Kind
      shell: bash
      run: |
        kind load image-archive /tmp/dynatrace-otel-collector.tar -n ${{ inputs.cluster-name }}
