name: "Create Kind Cluster"
description: "Creates a Kind cluster"
inputs:
  kind-version:
    required: false
    description: "Version of kind that should be used"
    # renovate: datasource=github-releases depName=kubernetes-sigs/kind
    default: "v0.27.0"
  k8s-version:
    required: false
    description: "Kubernetes version that should be used"
    # renovate: datasource=github-releases depName=kubernetes/kubernetes
    default: "v1.32.3"
  cluster-name:
    required: false
    description: "Name of the kind cluster"
    default: "kind"
env:
  # renovate: datasource=golang-version depName=go
  GO_VERSION: "1.24.1"
runs:
  using: "composite"
  steps:

    - name: Setup Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
        cache: false

    - name: Cache tools
      id: cache-tools
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: .tools
        key: e2e-tools-${{ runner.os }}-${{ hashFiles('internal/tools/go.sum') }}

    - name: Install tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p .tools
        touch .tools/*
        make install-tools

    - name: "Create single kind Cluster"
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        cluster_name: ${{ inputs.cluster-name }}
        version: ${{ inputs.kind-version }}
        node_image: "kindest/node:${{ inputs.k8s-version }}"
        kubectl_version: ${{ inputs.k8s-version }}
    
    - name: Download artifact
      uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
      with:
        name: dynatrace-otel-collector-image
        path: /tmp

    - name: Load Image into Kind
      shell: bash
      run: |
        kind load image-archive /tmp/dynatrace-otel-collector.tar -n ${{ inputs.cluster-name }}
