apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-logs-receiver-config
data:
  relay: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:5317
    exporters:
      debug:
        verbosity: detailed


    service:
      telemetry:
        metrics:
          level: none
      extensions: [health_check]
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters:
            - debug
