# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: prometheus-node-exporter
spec:
  steps:
    - name: step-00
      try:
        - assert:
            file: 00-assert.yaml
    - name: step-01
      try:
        - script:
            content: |
              # Wait for metrics to be available
              sleep 10
            timeout: 40s
            check:
              # This checks that Keptn returns active metrics
              (contains($stdout, 'keptn_promotion_count_total')): true