# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: prometheus-node-exporter
spec:
  steps:
    - name: step-00
      try:
        - assert:
            file: 00-assert.yaml
    - name: step-01
      try:
        - script:
            content: |
              # Wait for metrics to be available
              sleep 10
              # Query Dynatrace Metrics API for the node exporter metrics
              #curl -X GET "https://$DT_TENANT/api/v2/metrics/query" -H "accept: application/json; charset=utf-8" -H "Authorization: Api-Token $DT_API_TOKEN" -H "Content-Type: application/json; charset=utf-8" -d "{\"entitySelector\":\"type(HOST),tag(node-exporter)\",\"metricSelector\":\"builtin:metric.prometheus.node_exporter.*\"}"
            timeout: 40s
            check:
              # Basic check to see if the metrics are available
              ($error != null): true