version: 2
before:
  hooks:
    - make generate
    - mkdir -p bin

builds:
  - env:
      - CGO_ENABLED=0
      - GOWORK=off
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
      - -tags=timetzdata
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: s390x
    dir: build

sboms:
  - artifacts: archive

archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
nfpms:
  - file_name_template: >-
      {{ .PackageName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    contents:
      - src: internal/release/dynatrace-otel-collector.service
        dst: /lib/systemd/system/dynatrace-otel-collector.service
      - src: internal/release/dynatrace-otel-collector.conf
        dst: /etc/dynatrace-otel-collector/dynatrace-otel-collector.conf
    umask: 0o002
    scripts:
      preinstall: internal/release/preinstall.sh
      postinstall: internal/release/postinstall.sh
      preremove: internal/release/preremove.sh
    formats:
      - apk
      - deb
      - rpm
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    maintainer: "Dynatrace LLC <opensource@dynatrace.com>"
    vendor: "Dynatrace LLC"
    description: Dynatrace distribution of the OpenTelemetry Collector
    license: Apache 2.0
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-amd64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-amd64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-amd64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-arm64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-arm64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-arm64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-ppc64le
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-ppc64le
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-ppc64le
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-ppc64le
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: s390x
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-s390x
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-s390x
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-s390x
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-s390x
    build_flag_templates:
      - --pull
      - --platform=linux/s390x
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-amd64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-arm64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-ppc64le
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-s390x
  - name_template: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-amd64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-arm64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-ppc64le
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-s390x
  - name_template: public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}
    image_templates:
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-amd64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-arm64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-ppc64le
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-s390x
  - name_template: public.ecr.aws/dynatrace/dynatrace-otel-collector:latest
    image_templates:
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-amd64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-arm64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-ppc64le
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-s390x
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
