before:
  hooks:
    - make generate
    - mkdir -p bin

builds:
  - env:
      - CGO_ENABLED=0
      - GOWORK=off
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
      - -tags=timetzdata
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: build

sboms:
  - artifacts: archive

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-amd64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-amd64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-amd64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-arm64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-arm64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-arm64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
docker_manifests:
  - name_template: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-amd64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:{{ .Version }}-arm64
  - name_template: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest
    image_templates:
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-amd64
      - ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest-arm64
  - name_template: public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}
    image_templates:
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-amd64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:{{ .Version }}-arm64
  - name_template: public.ecr.aws/dynatrace/dynatrace-otel-collector:latest
    image_templates:
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-amd64
      - public.ecr.aws/dynatrace/dynatrace-otel-collector:latest-arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
