GOCMD?= go

# SRC_ROOT is the top of the source tree.
SRC_ROOT := $(shell git rev-parse --show-toplevel)

.PHONY: moddownload
moddownload:
	$(GOCMD) mod download

.PHONY: modtidy
modtidy:
	$(GOCMD) mod tidy

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR) $(DIST_DIR) $(BIN_DIR)
.PHONY: clean-tools
clean-tools:
	rm -rf $(TOOLS_BIN_DIR)

.PHONY: clean-all
clean-all: clean clean-tools
