name: "Deploy Prometheus Node Exporter on GH cluster"
description: "Deploys and exposes Prometheus Node Exporter on GH cluster"
runs:
  using: "composite"
  steps:
    - name: Install Prometheus Node exporter
      shell: bash
      run: ../../testbed/script/install_prometheus_node_exporter.sh
