mode: deployment
image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
  tag: 0.138.0
command:
  name: otelcol-contrib
resources:
  limits:
    memory: 512Mi
service:
  type: NodePort
ports:
  otlp-http:
    enabled: true
    containerPort: 30000
    nodePort: 30000
    protocol: TCP
alternateConfig:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  receivers:
    kafka:
      tls:
        insecure: true
      traces:
      metrics:
      logs:
      brokers: ["my-cluster-kafka-brokers.kafka.svc.cluster.local:9092"]
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:30000

  exporters:
    debug:
      verbosity: detailed
    kafka:
      brokers: ["my-cluster-kafka-brokers.kafka.svc.cluster.local:9092"]
      tls:
        insecure: true
      traces:
      metrics:
      logs:

  service:
    extensions: [health_check]
    pipelines:
      traces/send:
        receivers: [otlp]
        exporters: [kafka]
      traces/receive:
        receivers: [kafka]
        exporters: [debug]
      metrics/send:
        receivers: [otlp]
        exporters: [kafka]
      metrics/receive:
        receivers: [kafka]
        exporters: [debug]
      logs/send:
        receivers: [otlp]
        exporters: [kafka]
      logs/receive:
        receivers: [kafka]
        exporters: [debug]
