nameOverride: ""
fullnameOverride: "tiered-allocator"

replicaCount: 2

targetAllocator:
  podAnnotations:
    metrics.dynatrace.com/scrape: "true"
    metrics.dynatrace.com/port: "8080"
  image:
    repository: ghcr.io/dynatrace/otel-target-allocator/target-allocator
    # renovate: datasource=docker depName=ghcr.io/dynatrace/otel-target-allocator/target-allocator
    tag: 0.4.0
  serviceAccount:
    create: false
    name: "tiered-otel-allocator"
  service:
    port: 8080
  config:
    allocation_strategy: consistent-hashing
    collector_namespace: ${NAMESPACE}
    collector_selector:
      matchlabels:
        app.kubernetes.io/name: opentelemetry-collector
        app.kubernetes.io/instance: otel-scraper
    prometheus_cr:
      enabled: true
      scrapeInterval: 15s
      service_monitor_selector:
        matchlabels:
          prometheus.dynatrace.com: "true"
      pod_monitor_selector:
        matchlabels:
          prometheus.dynatrace.com: "true"
      scrape_config_selector:
        matchlabels:
          prometheus.dynatrace.com: "true"

  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 150Mi
