apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-collector
  namespace: dynatrace-collector
  labels:
    app.kubernetes.io/name: dynatrace-collector
    app.kubernetes.io/part-of: bindplane-poc
