exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

receivers:
  otlp:
    protocols:
      grpc:
      http:

extensions:
  health_check:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug]
  extensions: [health_check]
