apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-namespace: otel-collector
  name: dynatrace-opentelemetry-collector
  namespace: otel-collector

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10  
