# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: prometheus-node-exporter
spec:
  steps:
    - name: step-00
      try:
        - assert:
            file: 00-assert.yaml
    - name: step-01
      try:
        - script:
            content: |
              echo "Wait till the collector is ready and metrics are being processed"
              sleep 30
              echo "Checking if metrics are available..."
              bash ../../../testbed/scripts/get_dt_metrics.sh "(node_dmi_info:filter(and(or(eq(\"otel.scope.name\",\"otelcol/prometheusreceiver\")),or(eq(product_name,kind)))):splitBy(product_name):sort(value(auto,descending)):limit(20)):limit(100):names"
            timeout: 600s
            check:
              # Basic check to see if the metrics are available
              ($error == null): true
