# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: prometheus-node-exporter
spec:
  steps:
    - name: step-00
      try:
        - script:
            content: |
              # Portforward to collector in namespace otel-collector 
              # with service name dynatrace-opentelemetry-collector on port 54526 and 54527
              kubectl port-forward -n otel-collector svc/dynatrace-opentelemetry-collector 54526:54526 > /dev/null 2>&1 &
              port_forward_syslog_54526_pid=$!
              kubectl port-forward -n otel-collector svc/dynatrace-opentelemetry-collector 54527:54527 > /dev/null 2>&1 &
              port_forward_syslog_54527_pid=$!
              # trap to kill the port-forward process on script exit
              trap 'kill $port_forward_syslog_54526_pid' EXIT
              trap 'kill $port_forward_syslog_54527_pid' EXIT

              # Send Syslog message collector
              echo "<14>Test TCP syslog message from GitHub Test" >> /dev/tcp/127.0.0.1/54526
              echo "<14>Test UDP syslog message from GitHub Test" >> /dev/udp/127.0.0.1/54527

              # Wait for logs to be available
              sleep 10
              # Query Dynatrace Logs API and check if the logs are available              
              #curl -X GET "https://$DT_TENANT/api/v2/metrics/query" -H "accept: application/json; charset=utf-8" -H "Authorization: Api-Token $DT_API_TOKEN" -H "Content-Type: application/json; charset=utf-8" -d "{\"entitySelector\":\"type(HOST),tag(node-exporter)\",\"metricSelector\":\"builtin:metric.prometheus.node_exporter.*\"}"
            timeout: 40s
            check:
              # Basic check to see if the metrics are available
              ($error != null): true