apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-loadbalancer-config
data:
  relay: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
        verbosity: detailed
      loadbalancing:
        timeout: 10s
        retry_on_failure:
          enabled: true
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 1000
          sizer: requests
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          static:
            hostnames:
              - collector-receiver1.default.svc.cluster.local:5317
              - collector-receiver2.default.svc.cluster.local:6317

    service:
      telemetry:
        metrics:
          level: none
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters:
            - loadbalancing
            - debug
