apiVersion: v1
kind: Service
metadata:
  name: logs-receiver
spec:
  clusterIP: None
  ports:
    - name: otlp
      port: 5317
      targetPort: 5317
      protocol: TCP
      appProtocol: grpc
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: collector-receiver3
