mode: deployment
image:
  repository: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector
  tag: latest
command:
  name: dynatrace-otel-collector
extraEnvs:
- name: DT_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_API_TOKEN
- name: DT_API_ENDPOINT
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_API_ENDPOINT
resources:
  limits:
    memory: 512Mi
config:
  receivers:
    jaeger: null
    zipkin: null  
    prometheus:
      config:
        scrape_configs:
        - job_name: 'node-exporter'
          scrape_interval: 60s
          static_configs:
          - targets: ['prometheus-node-exporter.prometheus-node-exporter:9100']
        - job_name: opentelemetry-collector
          scrape_interval: 60s
          static_configs:
          - targets:
              - 127.0.0.1:8888

  processors:
    cumulativetodelta:

  exporters:
    logging: null
    otlphttp:
      endpoint: "$DT_API_ENDPOINT"
      headers:
        Authorization: "Api-Token $DT_API_TOKEN"

  service:
    pipelines:
      logs: null
      traces: null
      metrics:
        receivers: [prometheus]
        processors: [cumulativetodelta]
        exporters: [otlphttp]

