mode: deployment
image:
  repository: localhost:5000/collector
  tag: e2e-test
command:
  name: dynatrace-otel-collector
extraEnvs:
- name: DT_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_API_TOKEN
- name: DT_API_ENDPOINT
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_API_ENDPOINT
resources:
  limits:
    memory: 512Mi
ports:
  syslog-tcp:
    enabled: true
    containerPort: 54526
    servicePort: 54526
    hostPort: 54526
    protocol: TCP
  syslog-udp:
    enabled: true
    containerPort: 54527
    servicePort: 54527
    hostPort: 54527
    protocol: UDP    
config:
  receivers:
    jaeger: null
    zipkin: null  
    prometheus:
      config:
        scrape_configs:
        - job_name: 'node-exporter'
          scrape_interval: 60s
          static_configs:
          - targets: ['prometheus-node-exporter.prometheus-node-exporter:9100']
        - job_name: opentelemetry-collector
          scrape_interval: 60s
          static_configs:
          - targets:
              - 127.0.0.1:8888
    syslog/tcp:
      tcp:
        listen_address: "0.0.0.0:54526"
      protocol: rfc5424
      operators:
        - type: add
          field: attributes.log.source
          value: syslog
        - type: add
          field: attributes.device.type
          value: "github-tcp-rfc5424"
    syslog/udp:
      udp:
        listen_address: "0.0.0.0:54527"
      protocol: rfc5424
      operators:
        - type: add
          field: attributes.log.source
          value: syslog
        - type: add
          field: attributes.device.type
          value: "github-udp-rfc5424"

  processors:
    cumulativetodelta:

  exporters:
    logging: null
    otlphttp:
      endpoint: "$DT_API_ENDPOINT"
      headers:
        Authorization: "Api-Token $DT_API_TOKEN"

  service:
    pipelines:
      logs:
        receivers: [syslog/tcp, syslog/udp]
        exporters: [otlphttp]
      traces: null
      metrics:
        receivers: [prometheus]
        processors: [cumulativetodelta]
        exporters: [otlphttp]

