apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-receiver1-config
data:
  relay: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      debug:
        verbosity: detailed
      otlphttp:
        endpoint: https://fya1093d.dev.dynatracelabs.com/api/v2/otlp
        headers:
          Authorization: "Api-Token "

    service:
      telemetry:
        metrics:
          level: none
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters:
            - otlphttp
            - debug
        metrics:
          receivers: [otlp]
          processors: []
          exporters:
            - otlphttp
        logs:
          receivers: [otlp]
          processors: []
          exporters:
            - otlphttp
