apiVersion: v1
kind: Service
metadata:
  name: collector-receiver1
spec:
  type: ClusterIP
  ports:
    - name: otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
      appProtocol: grpc
  selector:
    app.kubernetes.io/name: collector-receiver1
    app.kubernetes.io/instance: collector-receiver1
